language: bash

sudo: false

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
  - tar xf shellcheck-latest.linux.x86_64.tar.xz

script:
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/gopack'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/gopack-build'

matrix:
  fast_finish: true
