language: bash

sudo: required

services:
  - docker

matrix:
  fast_finish: true

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
  - tar xf shellcheck-stable.linux.x86_64.tar.xz
  - ./shellcheck-stable/shellcheck --version
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - chmod +x perfecto-docker

script:
 - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck SOURCES/gopack'
 - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck SOURCES/gopack-build'
 - ./perfecto-docker gopack.spec
