#!/usr/bin/env bash

########################################################################################

APP="GoPack"
VER="1.5.0"

########################################################################################

NORM=0
BOLD=1
UNLN=4
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAG=35
CYAN=36
GREY=37
DARK=90

CL_NORM="\e[0m"
CL_BOLD="\e[0;${BOLD};49m"
CL_UNLN="\e[0;${UNLN};49m"
CL_RED="\e[0;${RED};49m"
CL_GREEN="\e[0;${GREEN};49m"
CL_YELLOW="\e[0;${YELLOW};49m"
CL_BLUE="\e[0;${BLUE};49m"
CL_MAG="\e[0;${MAG};49m"
CL_CYAN="\e[0;${CYAN};49m"
CL_GREY="\e[0;${GREY};49m"
CL_DARK="\e[0;${DARK};49m"
CL_BL_RED="\e[1;${RED};49m"
CL_BL_GREEN="\e[1;${GREEN};49m"
CL_BL_YELLOW="\e[1;${YELLOW};49m"
CL_BL_BLUE="\e[1;${BLUE};49m"
CL_BL_MAG="\e[1;${MAG};49m"
CL_BL_CYAN="\e[1;${CYAN};49m"
CL_BL_GREY="\e[1;${GREY};49m"

########################################################################################

SEPARATOR="--------------------------------------------------------------------------------"

TMP_TEMPLATE="gopack-XXXXXXXX"

SUPPORTED_ARCH_TYPES="tbz2 tar.bz2 tgz tar.gz tbz tar.bz"

SUPPORTED_ARGS="tmp output version revision tag branch !glide !dep !auto !no_colors 
 !verbose !help !usage"
SHORT_ARGS="T:tmp o:output v:version r:revision t:tag b:branch G:!glide D:!dep A:!auto
 nc:!no_colors V:!verbose h:!help"

EC_OK=0
EC_ERROR=1

# Path to temporary dir (String)
tmp="/tmp"

# -
# Temporary directory for sources
tmp_dir=""

########################################################################################

# Main function
#
# *: All unparsed argumens
#
# Code: No
# Echo: No
main() {
  if [[ ! -t 1 || -n "$no_colors" ]] ; then
    unset NORM BOLD UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_YELLOW CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
    unset CL_BL_RED CL_BL_GREEN CL_BL_YELLOW CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY
  fi

  if [[ -n "$help" || -n "$usage" || $# -eq 0 ]] ; then
    usage
    exit $EC_OK
  fi

  prepare
  process "$1"
}

# Check properties and arguments
#
# Code: No
# Echo: No
prepare() {
  if [[ -z "$tmp" ]] ; then
    error "Path to temporary directory can't be empty" $RED
    exit $EC_ERROR
  fi

  if [[ ! -d "$tmp" ]] ; then
    error "Temporary directory ${CL_BL_RED}${tmp}${CL_RED} doesn't exist" $RED
    exit $EC_ERROR
  fi

  if [[ ! -w "$tmp" || ! -r "$tmp" || ! -x "$tmp" ]] ; then
    error "Temporary directory ${CL_BL_RED}${tmp}${CL_RED} must be readable, writable and executable" $RED
    exit $EC_ERROR
  fi

  if ! isAppInstalled "go" ; then
    error "This utility require go. Install it first." $RED
    exit $EC_ERROR
  fi

  if ! isAppInstalled "curl" ; then
    error "This utility require curl. Install it first." $RED
    exit $EC_ERROR
  fi

  if [[ -n "$output" && -z $(getArchExt "$output") ]] ; then
    error "Unsupported output format" $RED
    exit $EC_ERROR
  fi
}

# Download and pack sources
#
# 1: Path (String)
#
# Code: No
# Echo: No
process() {
  local package arch_name

  package="$1"
  
  makeTempDir

  if [[ -z "$output" ]] ; then
    output=$(getOutputName "$package")
  fi

  # Allow redirects for stable import services
  git config --global http.https://pkg.re.followRedirects true &> /dev/null
  git config --global http.https://gopkg.in.followRedirects true &> /dev/null

  trap termExit SIGINT SIGQUIT SIGTERM

  showm "Setting temporary Go environment variables... " $BOLD

  setupGoEnv "$tmp_dir"

  show "DONE" $GREEN

  if ! checkoutCode "$package" "$tmp_dir" ; then
    cleanAndExit $EC_ERROR
  fi

  if [[ -n "$auto" ]] ; then
    findUsedDepsManager "$package" "$tmp_dir"
  fi

  if [[ -n "$glide" ]] ; then
    if ! installGlide ; then
      cleanAndExit $EC_ERROR
    fi

    if ! getDepsByGlide "$package" "$tmp_dir" ; then
      cleanAndExit $EC_ERROR
    fi
  elif [[ -n "$dep" ]] ; then
    if ! installDep ; then
      cleanAndExit $EC_ERROR
    fi

    if ! getDepsByDep "$package" "$tmp_dir" ; then
      cleanAndExit $EC_ERROR
    fi
  else
    if ! downloadDeps "$package" "$tmp_dir" ; then
      cleanAndExit $EC_ERROR
    fi
  fi

  arch_name=$(getArchName "$output")

  mv "${tmp_dir}/src" "${tmp_dir}/${arch_name}"
  mv "${tmp_dir}/REVISIONS" "${tmp_dir}/${arch_name}/"

  if ! packSources "$output" "$tmp_dir" ; then
    cleanAndExit $EC_ERROR
  fi

  cp "${tmp_dir}/${output}" .

  [[ -z "$verbose" ]] && show ""

  show "${CL_GREEN}Sources packed and saved as ${CL_BL_GREEN}${output}${CL_NORM}\n"

  cleanAndExit
}

# Create temporary directory
#
# Code: No
# Echo: No
makeTempDir() {
  tmp_dir=$(mktemp -d "${tmp:?}/$TMP_TEMPLATE")

  if [[ ! -d "$tmp_dir" ]] ; then
    error "Can't create temporary directory"
    exit $EC_ERROR
  fi
}

# Make directory for go sources and set GOPATH environment variable
#
# Code: No
# Echo: No
setupGoEnv() {
  local target_dir="$1"

  mkdir "$target_dir/src"
  mkdir "$target_dir/pkg"
  mkdir "$target_dir/bin"

  export GOPATH="$target_dir"
  export GOBIN="$target_dir/bin"
  export PATH="$target_dir/bin:$PATH"
}

# Checkout source code
#
# 1: Path to temporary dir (String)
# 2: Path to source code (String)
#
# Code: No
# Echo: No
checkoutCode() {
  local package tmp_dir git_path package_name

  package="$1"
  tmp_dir="$2"
  git_path="https://$package.git"
  package_name=$(basename "$package")

  showm "Downloading sources... " $BOLD

  if ! isHTTPStatusOk "$git_path" ; then
    show "ERROR" $RED
    error "Repository ${CL_BL_RED}${git_path}${CL_RED} is not accessible" $RED
    return 1
  fi

  mkdir -p "$tmp_dir/src/$package"

  if ! execCmd "git" "clone" "$git_path" "$tmp_dir/src/$package/" ; then
    error "Error while cloning repository ${CL_BL_RED}${git_path}" $RED
    return 1
  fi

  pushd "$tmp_dir/src/$package" &> /dev/null

    if [[ -n "$revision" ]] ; then
      showm "Switching HEAD to revision $revision... " $BOLD

      if ! execCmd "git" "checkout" "$revision" ; then
        error "Can't checkout revision ${CL_BL_RED}${revision}" $RED
        return 1
      fi
    fi

    if [[ -n "$branch" ]] ; then
      showm "Switching HEAD to branch $branch... " $BOLD

      if ! execCmd "git" "checkout" "$branch" ; then
        error "Can't checkout branch ${CL_BL_RED}${branch}" $RED
        return 1
      fi
    fi

    if [[ -n "$tag" ]] ; then
      showm "Switching HEAD to tag $tag... " $BOLD

      if ! execCmd "git" "checkout" "$tag" ; then
        error "Can't checkout tag ${CL_BL_RED}${tag}" $RED
        return 1
      fi
    fi

  popd &> /dev/null

  return 0
}

# Download dependencies for given package
#
# 1: Package name (String)
# 2: Path to temporary directory with sources (String)
#
# Code: Yes
# Echo: No
downloadDeps() {
  local package tmp_dir

  package="$1"
  tmp_dir="$2"

  showm "Downloading dependencies... " $BOLD

  pushd "$tmp_dir/src/$package" &> /dev/null

    if ! execCmd "go" "get" "-d" "-v" "./..." ; then
      error "Can't download package dependencies" $RED
      return 1
    fi

  popd &> /dev/null

  saveLatestCommitsHash "${tmp_dir}/src" "${tmp_dir}/REVISIONS"
  cleanPackDir "${tmp_dir}/src"

  return 0
}

# Try to find used dependency management tool
#
# 1: Package name (String)
# 2: Path to temporary directory with sources (String)
#
# Code: No
# Echo: No
findUsedDepsManager() {
  local package tmp_dir

  package="$1"
  tmp_dir="$2"

  if [[ $(find "$tmp_dir/src/$package" -name "Gopkg.toml" | wc -l) != "0" ]] ; then
    dep=true
  fi

  if [[ $(find "$tmp_dir/src/$package" -name "glide.yaml" | wc -l) != "0" ]] ; then
    glide=true
  fi
}

# Install latest version of glide
#
# Code: Yes
# Echo: No
installGlide() {
  if isAppInstalled "glide" ; then
    return 0
  fi

  showm "Installing glide... " $BOLD

  if ! execCmd "go" "get" "-v" "github.com/Masterminds/glide" ; then
    error "Can't install glide" $RED
    return 1
  fi

  return 0
}

# Download dependencies for given package using glide
#
# 1: Package name (String)
# 2: Path to temporary directory with sources (String)
#
# Code: Yes
# Echo: No
getDepsByGlide() {
  local package tmp_dir

  package="$1"
  tmp_dir="$2"

  showm "Downloading dependencies with glide... " $BOLD

  pushd "$tmp_dir/src/$package" &> /dev/null

    if ! execCmd "glide" "install" ; then
      error "Can't download package dependencies" $RED
      return 1
    fi

  popd &> /dev/null

  saveLatestCommitsHash "${tmp_dir}/src" "${tmp_dir}/REVISIONS"
  cleanPackDir "${tmp_dir}/src"

  return 0
}

# Install latest version of dep
#
# Code: Yes
# Echo: No
installDep() {
  if isAppInstalled "dep" ; then
    return 0
  fi

  showm "Installing dep... " $BOLD

  if ! execCmd "go" "get" "-v" "github.com/golang/dep/..." ; then
    error "Can't install dep" $RED
    return 1
  fi

  return 0
}

# Download dependencies for given package using glide
#
# 1: Package name (String)
# 2: Path to temporary directory with sources (String)
#
# Code: Yes
# Echo: No
getDepsByDep() {
  local package tmp_dir

  package="$1"
  tmp_dir="$2"

  showm "Downloading dependencies with dep... " $BOLD

  pushd "$tmp_dir/src/$package" &> /dev/null

    if ! execCmd "dep" "ensure" "-update" ; then
      error "Can't download package dependencies" $RED
      return 1
    fi

  popd &> /dev/null

  saveLatestCommitsHash "${tmp_dir}/src" "${tmp_dir}/REVISIONS"
  cleanPackDir "${tmp_dir}/src"

  return 0
}

# Save latest commit hash to file (currently supported only git)
#
# 1: Path to dir with sources (String)
# 2: Output file (String)
#
# Code: No
# Echo: No
saveLatestCommitsHash() {
  local dir output git_dir repo_dir head_hash

  dir="$1"
  output="$2"

  pushd "$dir" &> /dev/null

    while IFS= read -r -d '' git_dir ; do

      pushd "$git_dir" &> /dev/null

        pushd .. &> /dev/null

          repo_dir=$(dirname "${git_dir:2:9999}")
          head_hash=$(git rev-parse HEAD)

        popd &> /dev/null

        echo "$head_hash $repo_dir" >> "$output"

      popd &> /dev/null

    done < <(find . -name ".git" -type d -print0)

  popd &> /dev/null
}

# Remove repo data and CI services configs
#
# 1: Path to directory with sources (String)
#
# Code: No
# Echo: No
cleanPackDir() {
  local dir="$1"

  find "$dir" -type d -name ".git" -exec rm -rf {} \; 2> /dev/null
  find "$dir" -type f -name ".gitignore" -exec rm -f {} \; 2> /dev/null
  find "$dir" -type f -name ".gitattributes" -exec rm -f {} \; 2> /dev/null
  find "$dir" -type f -name ".gitmodules" -exec rm -f {} \; 2> /dev/null
  find "$dir" -type f -name ".travis.yml" -exec rm -f {} \; 2> /dev/null
  find "$dir" -type f -name ".drone.sec" -exec rm -f {} \; 2> /dev/null
  find "$dir" -type f -name ".drone.yml" -exec rm -f {} \; 2> /dev/null
  find "$dir" -type f -name ".hound.yml" -exec rm -f {} \; 2> /dev/null
  find "$dir" -type f -name ".vexor.yml" -exec rm -f {} \; 2> /dev/null
  find "$dir" -type f -name ".codebeatsettings" -exec rm -f {} \; 2> /dev/null
}

# Pack source into archive
#
# 1: Output file (String)
# 2: Temprary dir (String)
#
# Code: Yes
# Echo: No
packSources() {
  local output tmp_dir arch_name arch_ext

  output="$1"
  tmp_dir="$2"

  arch_name=$(getArchName "$output")
  arch_ext=$(getArchExt "$output")

  showm "Packing sources... " $BOLD

  pushd "${tmp_dir}" &> /dev/null

    if [[ "$arch_ext" == "tar.gz" || "$arch_ext" == "tgz" ]] ; then 
      if ! execCmd "tar" "czfv" "${arch_name}.${arch_ext}" "$arch_name" ; then
        error "Can't pack sources" $RED
        return 1
      fi
    elif [[ "$arch_ext" == "tar.bz2" || "$arch_ext" == "tbz2" || "$arch_ext" == "tar.bz" || "$arch_ext" == "tbz" ]] ; then
      if ! execCmd "tar" "cjfv" "${arch_name}.${arch_ext}" "$arch_name" ; then
        error "Can't pack sources" $RED
        return 1
      fi   
    else
      show "ERROR\n" $RED
      error "Unknown archive type" $RED
      return 1
    fi

  popd &> /dev/null

  return 0
}

# Generate output file name
#
# 1: Path (String)
#
# Code: No
# Echo: File name (String)
getOutputName() {
  local path base

  path="$1"
  base=$(basename "$path")

  if [[ -n "$version" ]] ; then
    echo "$base-$version.tar.bz2"
  else
    echo "$base.tar.bz2"
  fi
}

# Get archive name (without extension)
#
# 1: Archive name (String)
#
# Code: No
# Echo: Archive name without extension (String)
getArchName() {
  local file_name arch_type

  file_name=$(basename "$1")

  for arch_type in $SUPPORTED_ARCH_TYPES ; do
    file_name="${file_name/.${arch_type}/}"
  done

  echo "$file_name"
}

# Get archive extension
#
# 1: Archive name (String)
#
# Code: No
# Echo: Archive extension (String)
getArchExt() {
  local file_name arch_type

  file_name=$(basename "$1")

  for arch_type in $SUPPORTED_ARCH_TYPES ; do
    if [[ $file_name =~ $arch_type ]] ; then
      echo "$arch_type"
      return 0
    fi
  done

  echo ""
  return 1
}

# Execute some command
#
# *: Command and all arguments
#
# Code: Yes
# Echo: No
execCmd() {
  local status

  if [[ -n "$verbose" ]] ; then
    show "\n\n$SEPARATOR\n" $GREY
    $@
    status=$?
    show "\n$SEPARATOR\n" $GREY
  else
    $@ &> /dev/null
    
    status=$?

    if [[ $status -ne 0 ]] ; then
      show "ERROR" $RED
    else
      show "DONE" $GREEN
    fi
  fi

  return $status
}

# Check required dependencies
#
# *: Required apps
#
# Code: No
# Echo: No
isAppInstalled() {
  for app in "$@" ; do
    type -P "$app" &> /dev/null
    [[ $? -eq 1 ]] && return 1
  done

  return 0
}

# Check response status code for repo url
#
# 1: URL (String)
#
# Code: Yes
# Echo: No
isHTTPStatusOk() {
  local url code

  url="$1"
  code=$(curl -ILs -o /dev/null "$url" -w '%{http_code}')

  if [[ $code -ne 200 ]] ; then
    return 1
  fi

  return 0
}

# Clean temporary data and exit with given exit code
#
# 1: Path to temporary dir (String)
# 2: Exit code (Number) [Optional]
#
# Code: No
# Echo: No
cleanAndExit() {
  local code="${1:-$EC_OK}"

  if [[ -e "$tmp_dir" ]] ; then
    rm -rf "$tmp_dir"
  fi

  exit "$code"
}

# INT/QUIT/TERM signal handler
#
# Code: No
# Echo: No
termExit() {
  cleanAndExit $EC_ERROR
}

########################################################################################

# Print message to console
#
# 1: Message (String)
# 2: Color (Number) [Optional]
#
# Code: No
# Echo: No
show() {
  if [[ -n "$2" && -z "$no_colors" ]] ; then
    echo -e "\e[${2}m${1}\e[0m"
  else
    echo -e "$*"
  fi
}

# Print message without new line symbol to console
#
# 1: Message (String)
# 2: Color (Number) [Optional]
#
# Code: No
# Echo: No
showm() {
  if [[ -n "$2" && -z "$no_colors" ]] ; then
    echo -e -n "\e[${2}m${1}\e[0m"
  else
    echo -e -n "$*"
  fi
}

# Show formated message with option info
#
# 1: Option (String)
# 2: Description (String)
# 3: Arguments (String) [Optional]
#
# Code: No
# Echo: No
showo() {
  local optn optd optp optt optf breadcrumbs

  optn="$1"
  optd="$2"
  optp="$3"

  if [[ -n "$DARK" ]] ; then
    breadcrumbs="............................"
  else
    breadcrumbs="                            "
  fi

  if [[ -z "$optp" ]] ; then
    optt="$optn"
    optf=$(( 26 - ${#optt} ))
    echo -e "  ${CL_GREEN}${optn}${CL_NORM} ${CL_DARK}${breadcrumbs:0:$optf}${CL_NORM} $optd"
  else
    optt="$optn $optp"
    optf=$(( 26 - ${#optt} ))
    echo -e "  ${CL_GREEN}${optn}${CL_NORM} ${CL_GREY}${optp}${CL_NORM} ${CL_DARK}${breadcrumbs:0:$optf}${CL_NORM} $optd"
  fi
}

# Print error message
#
# 1: Message (String)
# 2: Message color (Number) [Optional]
#
# Code: No
# Echo: No
error() {
  show "$@" 1>&2
}

# Show usage info
#
# Code: No
# Echo: No
usage() {
  show ""
  show "${CL_BL_CYAN}$APP${CL_NORM} ${CL_CYAN}$VER${CL_NORM} - Simple tool for packing golang packages sources with all dependencies"
  show ""
  show "${CL_BOLD}Usage:${CL_NORM} gopack ${CL_GREEN}{options}${CL_NORM} package-path"
  show ""
  show "Options" $BOLD
  show ""
  showo "--output, -o"    "Output file name" "filename"
  showo "--version, -v"   "Package version" "version"
  showo "--revision, -r"  "Target revision" "revision"
  showo "--branch, -b"    "Target branch" "branch"
  showo "--tag, -t"       "Target tag" "tag"
  showo "--tmp, -T"       "Path to temporary directory (/tmp by default)" "path"
  showo "--glide, -G"     "Use glide for downloading dependencies"
  showo "--dep, -D"       "Use dep for downloading dependencies"
  showo "--auto, -A"      "Automatically find used dependency management tool"
  showo "--verbose, -V"   "Verbose output"
  showo "--no-color, -nc" "Disable colors in output"
  showo "--help, -h"      "Show this help message"
  show ""
  show "Examples" $BOLD
  show ""
  show "  gopack -v 1.0.1 github.com/essentialkaos/ssllabs_client"
  show "  Pack sources for version 1.0.1 and save result as ssllabs_client-1.0.1.tar.bz2" $DARK
  show ""
  show "  gopack -o ssllabs-client-1.0.1.tar.bz2 github.com/essentialkaos/ssllabs_client"
  show "  Pack sources for version 1.0.1 and save result as ssllabs-client-1.0.1.tar.bz2" $DARK
  show ""
  show "  gopack -o ssllabs-client-1.0.1.tgz -t v1.0.1 github.com/essentialkaos/ssllabs_client"
  show "  Fetch sources with tag v1.0.1, pack sources for version 1.0.1 and save result " $DARK
  show "  as ssllabs-client-1.0.1.tgz" $DARK
  show ""
  show "Copyright (C) 2009-$(date +%Y) ESSENTIAL KAOS" $DARK
  show "Essential Kaos Open Source License <https://essentialkaos.com/ekol>" $DARK
  show ""
}

# Print message about unsupported argument
#
# 1: Argument (String)
#
# Code: No
# Echo: No
showArgWarn() {
  error "Unknown argument $1" $RED
  exit 1
}

## ARGUMENTS PARSING 3 #################################################################

[[ $# -eq 0 ]] && main && exit $?

unset arg argn argm argv argt argk

argv="$*" ; argt=""

while [[ -n "$1" ]] ; do
  if [[ "$1" =~ \  && -n "$argn" ]] ; then
    declare "$argn=$1"

    unset argn && shift && continue
  elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
    argm=${1:1}

    if [[ \ $SHORT_ARGS\  =~ \ $argm:!?([a-zA-Z0-9_]*) ]] ; then
      arg="${BASH_REMATCH[1]}"
    else
      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
      shift && continue
    fi

    if [[ -z "$argn" ]] ; then
      argn=$arg
    else
      [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
      argn=$arg
    fi

    if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
      shift && continue
    fi

    if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
      declare "$argn=true" ; unset argn ; argk=true
    else
      unset argk
    fi

    shift && continue
  elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
    arg=${1:2}

    if [[ $arg == *=* ]] ; then
      IFS="=" read -ra arg <<< "$arg"

      argm="${arg[0]}" ; argm=${argm//-/_}

      if [[ ! $SUPPORTED_ARGS\  =~ $argm\  ]] ; then
        declare -F showArgWarn &>/dev/null && showArgWarn "--${arg[0]//_/-}"
        shift && continue
      fi

      [[ -n "${!argm}" && $MERGEABLE_ARGS\  =~ $argm\  ]] && declare "$argm=${!argm} ${arg[@]:1:99}" || declare "$argm=${arg[@]:1:99}"

      unset argm && shift && continue
    else
      arg=${arg//-/_}

      if [[ -z "$argn" ]] ; then
        argn=$arg
      else
        [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
        argn=$arg
      fi

      if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
        declare -F showArgWarn &>/dev/null && showArgWarn "--${argn//_/-}"
        shift && continue
      fi

      if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
        declare "$argn=true" ; unset argn ; argk=true
      else
        unset argk
      fi

      shift && continue
    fi
  else
    if [[ -n "$argn" ]] ; then
      [[ -n "${!argn}" && $MERGEABLE_ARGS\  =~ $argn\  ]] && declare "$argn=${!argn} $1" || declare "$argn=$1"

      unset argn && shift && continue
    fi
  fi

  argt="$argt $1" ; shift

done

[[ -n "$argn" ]] && declare "$argn=true"

unset arg argn argm argk

[[ -n "$KEEP_ARGS" ]] && main $argv || main ${argt:1:9999}

########################################################################################
