name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    env:
      SHELLCHECK_VERSION: 0.7.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Shellcheck
        run: |
          wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
          tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
          mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest

      - name: Print Shellcheck version info
        run: ./shellcheck-latest/shellcheck --version

      - name: Check scripts
        run: |
          bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/gopack'
          bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/gopack-build'

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Perfecto docker image
        uses: docker://essentialkaos/perfecto:slim
        with:
          args: --version

      - name: Install perfecto-docker
        run: |
          wget https://kaos.sh/perfecto/perfecto-docker
          chmod +x perfecto-docker

      - name: Run Perfecto check
        env:
          IMAGE: essentialkaos/perfecto:slim
        run: ./perfecto-docker gopack.spec
